<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW0058" name="Default test" tests="5" failures="1" timestamp="2 Aug 2016 11:53:28 GMT" time="12.414" errors="0">
  <testcase name="testLogonYandex" time="1.596" classname="com.epam.elena_stepuro.framework.reporting.run_tests.test.YandexTest">
    <failure type="java.lang.RuntimeException" message="Test!">
      <![CDATA[java.lang.RuntimeException: Test!
	at com.epam.elena_stepuro.framework.reporting.run_tests.test.YandexTest.testLogonYandex(YandexTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- testLogonYandex -->
  <testcase name="testWriteSaveLetter" time="0.0" classname="com.epam.elena_stepuro.framework.reporting.run_tests.test.YandexTest">
    <skipped/>
  </testcase> <!-- testWriteSaveLetter -->
  <testcase name="testCheckDrafts" time="0.0" classname="com.epam.elena_stepuro.framework.reporting.run_tests.test.YandexTest">
    <skipped/>
  </testcase> <!-- testCheckDrafts -->
  <testcase name="testClearDrafts" time="0.0" classname="com.epam.elena_stepuro.framework.reporting.run_tests.test.YandexTest">
    <skipped/>
  </testcase> <!-- testClearDrafts -->
  <testcase name="testClearSendLetters" time="0.0" classname="com.epam.elena_stepuro.framework.reporting.run_tests.test.YandexTest">
    <skipped/>
  </testcase> <!-- testClearSendLetters -->
</testsuite> <!-- Default test -->
